
CREATE TABLE [dbo].[Currency]
(
	[Id]			[smallint]		NOT NULL,
	[Code]			[nvarchar](5)	NOT NULL,
	[BalanceStep]	[float]			NULL,
	
	CONSTRAINT [PK_Currency] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 
ON [PRIMARY]

GO